name: Build .NET Framework Desktop App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Restore NuGet packages
      run: nuget restore PMJAReviewExporter.sln

    - name: Build with MSBuild
      run: msbuild PMJAReviewExporter.sln /p:Configuration=Release
